# --- MongoDB Service ---
# A Service creates a stable network endpoint for the MongoDB Pod.
# Your Node.js app will connect to the database using the name 'mongodb'.
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
# --- MongoDB Deployment ---
# A Deployment ensures that a specified number of Pods are always running.
# In this case, it will always maintain one MongoDB Pod.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4 # Use a standard MongoDB image
          ports:
            - containerPort: 27017
